/*
    Migration Script: Data - [EmailTemplateComponents]
    Phase: 900 - Data
    Script: cu_900_04_dbo.EmailTemplateComponents.sql
    Description: Inserts data into [dbo].[EmailTemplateComponents]
    
    Execution Order: 4
    Record Count: 18
*/

SET NOCOUNT ON;
GO

PRINT 'Inserting data into [dbo].[EmailTemplateComponents]...';
GO

IF NOT EXISTS (SELECT TOP 1 1 FROM [dbo].[EmailTemplateComponents])
BEGIN
    SET IDENTITY_INSERT [dbo].[EmailTemplateComponents] ON;

    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (1, N'header', N'Default Header', N'<div style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);padding:40px 20px;text-align:center"><h1 style="color:white;margin:0;font-size:28px;font-weight:600">{{platformName}}</h1><p style="color:rgba(255,255,255,0.9);margin:10px 0 0;font-size:14px">Connecting you with amazing vendors</p></div>', N'{{platformName}} - Connecting you with amazing vendors', N'Default header with gradient', 1, CAST(N'2025-10-30T20:44:22.060' AS DateTime), CAST(N'2025-10-30T20:44:22.060' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (2, N'footer', N'Default Footer', N'<div style="background:#f8f9fa;padding:30px 20px;text-align:center;border-top:1px solid #e9ecef"><p style="color:#6c757d;margin:0 0 10px;font-size:14px">Need help? <a href="mailto:support@{{platformUrl}}" style="color:#667eea">support@{{platformUrl}}</a></p><p style="color:#adb5bd;margin:10px 0 0;font-size:12px">© {{currentYear}} {{platformName}}. All rights reserved.</p></div>', N'© {{currentYear}} {{platformName}}. Contact: support@{{platformUrl}}', N'Default footer', 1, CAST(N'2025-10-30T20:44:22.067' AS DateTime), CAST(N'2025-10-30T20:44:22.067' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (3, N'body', N'2FA Code', N'<div style="padding:40px 20px;background:white"><h2 style="color:#333;margin:0 0 20px">Verification Code</h2><p style="color:#666;margin:0 0 20px">Hello {{userName}},</p><p style="color:#666;margin:0 0 30px">Your verification code is:</p><div style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);padding:20px;border-radius:8px;text-align:center;margin:0 0 30px"><span style="color:white;font-size:32px;font-weight:bold;letter-spacing:8px">{{code}}</span></div><p style="color:#666;margin:0">Expires in <strong>10 minutes</strong>.</p></div>', N'Your code: {{code}}. Expires in 10 minutes.', N'2FA verification', 1, CAST(N'2025-10-30T20:44:22.070' AS DateTime), CAST(N'2025-10-30T20:44:22.070' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (4, N'body', N'Booking Request', N'<div style="padding:40px 20px;background:white"><h2 style="color:#333;margin:0 0 20px">New Booking Request</h2><p style="color:#666;margin:0 0 20px">Hello {{vendorName}},</p><p style="color:#666;margin:0 0 30px">New request from <strong>{{clientName}}</strong>.</p><div style="background:#f8f9fa;padding:20px;border-radius:8px;border-left:4px solid #667eea;margin:0 0 30px"><h3 style="color:#333;margin:0 0 15px;font-size:16px">Event Details</h3><p style="margin:5px 0"><strong>Service:</strong> {{serviceName}}</p><p style="margin:5px 0"><strong>Date:</strong> {{eventDate}}</p><p style="margin:5px 0"><strong>Location:</strong> {{location}}</p><p style="margin:5px 0"><strong>Budget:</strong> {{budget}}</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">View Request</a></p></div>', N'New request from {{clientName}}. Service: {{serviceName}}, Date: {{eventDate}}. View: {{dashboardUrl}}', N'Booking request for vendor', 1, CAST(N'2025-10-30T20:44:22.077' AS DateTime), CAST(N'2025-10-30T20:44:22.077' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (5, N'body', N'Booking Accepted', N'<div style="padding:40px 20px;background:white"><h2 style="color:#28a745;margin:0 0 20px">? Booking Accepted!</h2><p style="color:#666;margin:0 0 20px">Hello {{clientName}},</p><p style="color:#666;margin:0 0 30px"><strong>{{vendorName}}</strong> accepted your request for <strong>{{serviceName}}</strong>!</p><div style="background:#d4edda;padding:20px;border-radius:8px;border-left:4px solid #28a745;margin:0 0 30px"><h3 style="color:#155724;margin:0 0 15px;font-size:16px">Next Steps</h3><p style="color:#155724;margin:5px 0">• Review booking details</p><p style="color:#155724;margin:5px 0">• Complete payment</p><p style="color:#155724;margin:5px 0">• Message vendor</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">View Booking</a></p></div>', N'{{vendorName}} accepted your request for {{serviceName}}! View: {{dashboardUrl}}', N'Booking accepted notification', 1, CAST(N'2025-10-30T20:44:22.080' AS DateTime), CAST(N'2025-10-30T20:44:22.080' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (6, N'body', N'Booking Rejected', N'<div style="padding:40px 20px;background:white"><h2 style="color:#dc3545;margin:0 0 20px">Booking Update</h2><p style="color:#666;margin:0 0 20px">Hello {{clientName}},</p><p style="color:#666;margin:0 0 30px"><strong>{{vendorName}}</strong> cannot accept your request for <strong>{{serviceName}}</strong> on {{eventDate}}.</p><p style="color:#666;margin:0 0 30px">Many other vendors can help make your event amazing!</p><p style="text-align:center;margin:0"><a href="{{searchUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">Find Vendors</a></p></div>', N'{{vendorName}} cannot accept your request. Find other vendors: {{searchUrl}}', N'Booking rejected notification', 1, CAST(N'2025-10-30T20:44:22.083' AS DateTime), CAST(N'2025-10-30T20:44:22.083' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (7, N'body', N'Message From Vendor', N'<div style="padding:40px 20px;background:white"><h2 style="color:#333;margin:0 0 20px">New Message from {{vendorName}}</h2><p style="color:#666;margin:0 0 20px">Hello {{clientName}},</p><div style="background:#f8f9fa;padding:20px;border-radius:8px;border-left:4px solid #667eea;margin:0 0 30px"><p style="color:#333;margin:0">{{messageContent}}</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">Reply</a></p></div>', N'Message from {{vendorName}}: {{messageContent}}. Reply: {{dashboardUrl}}', N'Message from vendor', 1, CAST(N'2025-10-30T20:44:22.087' AS DateTime), CAST(N'2025-10-30T20:44:22.087' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (8, N'body', N'Message From Client', N'<div style="padding:40px 20px;background:white"><h2 style="color:#333;margin:0 0 20px">New Message from {{clientName}}</h2><p style="color:#666;margin:0 0 20px">Hello {{vendorName}},</p><div style="background:#f8f9fa;padding:20px;border-radius:8px;border-left:4px solid #667eea;margin:0 0 30px"><p style="color:#333;margin:0">{{messageContent}}</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">Reply</a></p></div>', N'Message from {{clientName}}: {{messageContent}}. Reply: {{dashboardUrl}}', N'Message from client', 1, CAST(N'2025-10-30T20:44:22.090' AS DateTime), CAST(N'2025-10-30T20:44:22.090' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (9, N'body', N'Payment Received', N'<div style="padding:40px 20px;background:white"><h2 style="color:#28a745;margin:0 0 20px">?? Payment Received</h2><p style="color:#666;margin:0 0 20px">Hello {{vendorName}},</p><p style="color:#666;margin:0 0 30px">Payment from <strong>{{clientName}}</strong>.</p><div style="background:#d4edda;padding:20px;border-radius:8px;border-left:4px solid #28a745;margin:0 0 30px"><h3 style="color:#155724;margin:0 0 15px;font-size:16px">Details</h3><p style="color:#155724;margin:5px 0;font-size:20px;font-weight:600"><strong>Amount:</strong> {{amount}}</p><p style="color:#155724;margin:5px 0"><strong>Service:</strong> {{serviceName}}</p><p style="color:#155724;margin:5px 0"><strong>Event:</strong> {{eventDate}}</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">View Payment</a></p></div>', N'Payment received: {{amount}} for {{serviceName}}. View: {{dashboardUrl}}', N'Payment received notification', 1, CAST(N'2025-10-30T20:44:22.097' AS DateTime), CAST(N'2025-10-30T20:44:22.097' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (10, N'header', N'Default Header', N'<div style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);padding:40px 20px;text-align:center"><h1 style="color:white;margin:0;font-size:28px;font-weight:600">{{platformName}}</h1><p style="color:rgba(255,255,255,0.9);margin:10px 0 0;font-size:14px">Connecting you with amazing vendors</p></div>', N'{{platformName}} - Connecting you with amazing vendors', N'Default header with gradient', 1, CAST(N'2025-11-26T01:05:11.057' AS DateTime), CAST(N'2025-11-26T01:05:11.057' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (11, N'footer', N'Default Footer', N'<div style="background:#f8f9fa;padding:30px 20px;text-align:center;border-top:1px solid #e9ecef"><p style="color:#6c757d;margin:0 0 10px;font-size:14px">Need help? <a href="mailto:support@{{platformUrl}}" style="color:#667eea">support@{{platformUrl}}</a></p><p style="color:#adb5bd;margin:10px 0 0;font-size:12px">Â© {{currentYear}} {{platformName}}. All rights reserved.</p></div>', N'Â© {{currentYear}} {{platformName}}. Contact: support@{{platformUrl}}', N'Default footer', 1, CAST(N'2025-11-26T01:05:11.087' AS DateTime), CAST(N'2025-11-26T01:05:11.087' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (12, N'body', N'2FA Code', N'<div style="padding:40px 20px;background:white"><h2 style="color:#333;margin:0 0 20px">Verification Code</h2><p style="color:#666;margin:0 0 20px">Hello {{userName}},</p><p style="color:#666;margin:0 0 30px">Your verification code is:</p><div style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);padding:20px;border-radius:8px;text-align:center;margin:0 0 30px"><span style="color:white;font-size:32px;font-weight:bold;letter-spacing:8px">{{code}}</span></div><p style="color:#666;margin:0">Expires in <strong>10 minutes</strong>.</p></div>', N'Your code: {{code}}. Expires in 10 minutes.', N'2FA verification', 1, CAST(N'2025-11-26T01:05:11.093' AS DateTime), CAST(N'2025-11-26T01:05:11.093' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (13, N'body', N'Booking Request', N'<div style="padding:40px 20px;background:white"><h2 style="color:#333;margin:0 0 20px">New Booking Request</h2><p style="color:#666;margin:0 0 20px">Hello {{vendorName}},</p><p style="color:#666;margin:0 0 30px">New request from <strong>{{clientName}}</strong>.</p><div style="background:#f8f9fa;padding:20px;border-radius:8px;border-left:4px solid #667eea;margin:0 0 30px"><h3 style="color:#333;margin:0 0 15px;font-size:16px">Event Details</h3><p style="margin:5px 0"><strong>Service:</strong> {{serviceName}}</p><p style="margin:5px 0"><strong>Date:</strong> {{eventDate}}</p><p style="margin:5px 0"><strong>Location:</strong> {{location}}</p><p style="margin:5px 0"><strong>Budget:</strong> {{budget}}</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">View Request</a></p></div>', N'New request from {{clientName}}. Service: {{serviceName}}, Date: {{eventDate}}. View: {{dashboardUrl}}', N'Booking request for vendor', 1, CAST(N'2025-11-26T01:05:11.097' AS DateTime), CAST(N'2025-11-26T01:05:11.097' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (14, N'body', N'Booking Accepted', N'<div style="padding:40px 20px;background:white"><h2 style="color:#28a745;margin:0 0 20px">âœ“ Booking Accepted!</h2><p style="color:#666;margin:0 0 20px">Hello {{clientName}},</p><p style="color:#666;margin:0 0 30px"><strong>{{vendorName}}</strong> accepted your request for <strong>{{serviceName}}</strong>!</p><div style="background:#d4edda;padding:20px;border-radius:8px;border-left:4px solid #28a745;margin:0 0 30px"><h3 style="color:#155724;margin:0 0 15px;font-size:16px">Next Steps</h3><p style="color:#155724;margin:5px 0">â€¢ Review booking details</p><p style="color:#155724;margin:5px 0">â€¢ Complete payment</p><p style="color:#155724;margin:5px 0">â€¢ Message vendor</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">View Booking</a></p></div>', N'{{vendorName}} accepted your request for {{serviceName}}! View: {{dashboardUrl}}', N'Booking accepted notification', 1, CAST(N'2025-11-26T01:05:11.100' AS DateTime), CAST(N'2025-11-26T01:05:11.100' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (15, N'body', N'Booking Rejected', N'<div style="padding:40px 20px;background:white"><h2 style="color:#dc3545;margin:0 0 20px">Booking Update</h2><p style="color:#666;margin:0 0 20px">Hello {{clientName}},</p><p style="color:#666;margin:0 0 30px"><strong>{{vendorName}}</strong> cannot accept your request for <strong>{{serviceName}}</strong> on {{eventDate}}.</p><p style="color:#666;margin:0 0 30px">Many other vendors can help make your event amazing!</p><p style="text-align:center;margin:0"><a href="{{searchUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">Find Vendors</a></p></div>', N'{{vendorName}} cannot accept your request. Find other vendors: {{searchUrl}}', N'Booking rejected notification', 1, CAST(N'2025-11-26T01:05:11.107' AS DateTime), CAST(N'2025-11-26T01:05:11.107' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (16, N'body', N'Message From Vendor', N'<div style="padding:40px 20px;background:white"><h2 style="color:#333;margin:0 0 20px">New Message from {{vendorName}}</h2><p style="color:#666;margin:0 0 20px">Hello {{clientName}},</p><div style="background:#f8f9fa;padding:20px;border-radius:8px;border-left:4px solid #667eea;margin:0 0 30px"><p style="color:#333;margin:0">{{messageContent}}</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">Reply</a></p></div>', N'Message from {{vendorName}}: {{messageContent}}. Reply: {{dashboardUrl}}', N'Message from vendor', 1, CAST(N'2025-11-26T01:05:11.110' AS DateTime), CAST(N'2025-11-26T01:05:11.110' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (17, N'body', N'Message From Client', N'<div style="padding:40px 20px;background:white"><h2 style="color:#333;margin:0 0 20px">New Message from {{clientName}}</h2><p style="color:#666;margin:0 0 20px">Hello {{vendorName}},</p><div style="background:#f8f9fa;padding:20px;border-radius:8px;border-left:4px solid #667eea;margin:0 0 30px"><p style="color:#333;margin:0">{{messageContent}}</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">Reply</a></p></div>', N'Message from {{clientName}}: {{messageContent}}. Reply: {{dashboardUrl}}', N'Message from client', 1, CAST(N'2025-11-26T01:05:11.117' AS DateTime), CAST(N'2025-11-26T01:05:11.117' AS DateTime));
    INSERT [dbo].[EmailTemplateComponents] ([ComponentID], [ComponentType], [ComponentName], [HtmlContent], [TextContent], [Description], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (18, N'body', N'Payment Received', N'<div style="padding:40px 20px;background:white"><h2 style="color:#28a745;margin:0 0 20px">ðŸ’° Payment Received</h2><p style="color:#666;margin:0 0 20px">Hello {{vendorName}},</p><p style="color:#666;margin:0 0 30px">Payment from <strong>{{clientName}}</strong>.</p><div style="background:#d4edda;padding:20px;border-radius:8px;border-left:4px solid #28a745;margin:0 0 30px"><h3 style="color:#155724;margin:0 0 15px;font-size:16px">Details</h3><p style="color:#155724;margin:5px 0;font-size:20px;font-weight:600"><strong>Amount:</strong> {{amount}}</p><p style="color:#155724;margin:5px 0"><strong>Service:</strong> {{serviceName}}</p><p style="color:#155724;margin:5px 0"><strong>Event:</strong> {{eventDate}}</p></div><p style="text-align:center;margin:0"><a href="{{dashboardUrl}}" style="display:inline-block;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:14px 30px;text-decoration:none;border-radius:6px;font-weight:600">View Payment</a></p></div>', N'Payment received: {{amount}} for {{serviceName}}. View: {{dashboardUrl}}', N'Payment received notification', 1, CAST(N'2025-11-26T01:05:11.120' AS DateTime), CAST(N'2025-11-26T01:05:11.120' AS DateTime));

    SET IDENTITY_INSERT [dbo].[EmailTemplateComponents] OFF;

    PRINT 'Inserted 18 records into [dbo].[EmailTemplateComponents].';
END
ELSE
BEGIN
    PRINT 'Table [dbo].[EmailTemplateComponents] already contains data. Skipping.';
END
GO
