/*
    Migration Script: Data - [EmailLogs]
    Phase: 900 - Data
    Script: cu_900_13_dbo.EmailLogs.sql
    Description: Inserts data into [admin].[EmailLogs]
    
    Execution Order: 13
    Record Count: 35
*/

SET NOCOUNT ON;
GO

PRINT 'Inserting data into [admin].[EmailLogs]...';
GO

IF NOT EXISTS (SELECT TOP 1 1 FROM [admin].[EmailLogs])
BEGIN
    SET IDENTITY_INSERT [admin].[EmailLogs] ON;

    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (1, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Invalid login: 535 5.7.8 Authentication failed', NULL, NULL, NULL, CAST(N'2025-10-30T21:51:09.080' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (2, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Invalid login: 535 5.7.8 Authentication failed', NULL, NULL, NULL, CAST(N'2025-10-30T22:00:08.413' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (3, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:05:15.470' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (4, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:05:32.323' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (5, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:06:04.560' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (6, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:06:12.440' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (7, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:06:13.677' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (8, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:06:14.010' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (9, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:06:14.190' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (10, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:06:14.220' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (11, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:06:58.647' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (12, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:06:58.683' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (13, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:07:33.067' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (14, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Connection timeout', NULL, NULL, NULL, CAST(N'2025-10-30T22:10:04.253' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (15, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Your Verification Code', N'failed', N'BREVO_API_KEY not configured', NULL, NULL, NULL, CAST(N'2025-10-30T22:10:26.650' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (16, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'BREVO_API_KEY not configured', NULL, NULL, NULL, CAST(N'2025-10-30T22:10:26.687' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (17, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Your Verification Code', N'failed', N'Brevo API error: 401 - API Key is not enabled', NULL, NULL, NULL, CAST(N'2025-10-30T22:16:35.323' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (18, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Brevo API error: 401 - API Key is not enabled', NULL, NULL, NULL, CAST(N'2025-10-30T22:16:35.393' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (19, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Your Verification Code', N'failed', N'Brevo API error: 401 - API Key is not enabled', NULL, NULL, NULL, CAST(N'2025-10-30T22:19:03.850' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (20, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Brevo API error: 401 - API Key is not enabled', NULL, NULL, NULL, CAST(N'2025-10-30T22:19:03.903' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (21, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Your Verification Code', N'failed', N'Brevo API error: 401 - API Key is not enabled', NULL, NULL, NULL, CAST(N'2025-10-30T22:24:11.250' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (22, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Brevo API error: 401 - API Key is not enabled', NULL, NULL, NULL, CAST(N'2025-10-30T22:24:11.283' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (23, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Your Verification Code', N'failed', N'Brevo API error: 401 - We have detected you are using an unrecognised IP address 52.41.36.82. If you performed this action make sure to add the new IP address in this link: https://app.brevo.com/security/authorised_ips', NULL, NULL, NULL, CAST(N'2025-10-30T22:32:10.100' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (24, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Error', N'failed', N'Brevo API error: 401 - We have detected you are using an unrecognised IP address 52.41.36.82. If you performed this action make sure to add the new IP address in this link: https://app.brevo.com/security/authorised_ips', NULL, NULL, NULL, CAST(N'2025-10-30T22:32:10.170' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (25, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Your Verification Code', N'sent', NULL, NULL, NULL, NULL, CAST(N'2025-10-30T22:33:36.343' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (26, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Your Verification Code', N'sent', NULL, NULL, NULL, NULL, CAST(N'2025-10-30T22:34:51.190' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (27, N'auth_2fa', N'sami.s.musa@gmail.com', N'User', N'Your Verification Code', N'sent', NULL, NULL, NULL, NULL, CAST(N'2025-10-31T03:14:25.153' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (28, N'auth_2fa', N'vu99@samtest.com', N'User', N'Your Verification Code', N'sent', NULL, NULL, NULL, NULL, CAST(N'2025-10-31T13:24:28.687' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (29, N'auth_2fa', N'vu99@samtest.com', N'User', N'Your Verification Code', N'sent', NULL, NULL, NULL, NULL, CAST(N'2025-10-31T13:25:48.853' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (30, N'auth_2fa', N'vu99@samtest.com', N'User', N'Your Verification Code', N'failed', N'Brevo API error: 401 - Key not found', NULL, NULL, NULL, CAST(N'2025-12-12T00:34:15.560' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (31, N'auth_2fa', N'vu99@samtest.com', N'User', N'Error', N'failed', N'Brevo API error: 401 - Key not found', NULL, NULL, NULL, CAST(N'2025-12-12T00:34:15.757' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (32, N'auth_2fa', N'vu99@samtest.com', N'User', N'Your Verification Code', N'failed', N'Brevo API error: 401 - Key not found', NULL, NULL, NULL, CAST(N'2025-12-12T00:42:29.743' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (33, N'auth_2fa', N'vu99@samtest.com', N'User', N'Error', N'failed', N'Brevo API error: 401 - Key not found', NULL, NULL, NULL, CAST(N'2025-12-12T00:42:29.870' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (34, N'auth_2fa', N'vu99@samtest.com', N'User', N'Your Verification Code', N'failed', N'Brevo API error: 401 - We have detected you are using an unrecognised IP address 74.220.48.241. If you performed this action make sure to add the new IP address in this link: https://app.brevo.com/security/authorised_ips', NULL, NULL, NULL, CAST(N'2025-12-12T01:04:09.210' AS DateTime));
    INSERT [admin].[EmailLogs] ([EmailLogID], [TemplateKey], [RecipientEmail], [RecipientName], [Subject], [Status], [ErrorMessage], [UserID], [BookingID], [Metadata], [SentAt]) VALUES (35, N'auth_2fa', N'vu99@samtest.com', N'User', N'Error', N'failed', N'Brevo API error: 401 - We have detected you are using an unrecognised IP address 74.220.48.241. If you performed this action make sure to add the new IP address in this link: https://app.brevo.com/security/authorised_ips', NULL, NULL, NULL, CAST(N'2025-12-12T01:04:09.290' AS DateTime));

    SET IDENTITY_INSERT [admin].[EmailLogs] OFF;

    PRINT 'Inserted 35 records into [admin].[EmailLogs].';
END
ELSE
BEGIN
    PRINT 'Table [admin].[EmailLogs] already contains data. Skipping.';
END
GO
