/*
    Migration Script: Data - [EmailTemplates]
    Phase: 1000 - Data
    Script: pb_1000_04_EmailTemplates.sql
    Description: Inserts email templates linking to components
    
    This script contains all 69 email template definitions with:
    - Template keys for programmatic access
    - Component ID references (header, body, footer)
    - Subject lines with variable placeholders
    - Category groupings
    - Available variables for each template
    
    Generated: 2026-02-11T21:46:35.802Z
    Template Count: 69
*/

SET NOCOUNT ON;
GO

PRINT 'Inserting data into [admin].[EmailTemplates]...';
GO

IF NOT EXISTS (SELECT TOP 1 1 FROM [admin].[EmailTemplates])
BEGIN
    SET IDENTITY_INSERT [admin].[EmailTemplates] ON;

    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (1, N'auth_2fa', N'2FA Verification', 1, 3, 2, N'{{code}} - Sign In Verification Code', N'authentication', N'["userName","code","platformName","platformUrl","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (2, N'booking_request_vendor', N'Booking Request to Vendor', 1, 4, 2, N'New Booking Request from {{clientName}}', N'booking', N'["vendorName","clientName","serviceName","eventDate","location","budget","dashboardUrl","platformName","platformUrl","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (3, N'booking_accepted_client', N'Booking Accepted', 1, 5, 2, N'{{vendorName}} Accepted Your Booking', N'booking', N'["clientName","vendorName","serviceName","dashboardUrl","platformName","platformUrl","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (4, N'booking_rejected_client', N'Booking Rejected', 1, 6, 2, N'Booking Update - {{vendorName}}', N'booking', N'["clientName","vendorName","serviceName","eventDate","searchUrl","platformName","platformUrl","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (5, N'message_vendor_to_client', N'Message from Vendor', 1, 7, 2, N'New Message from {{vendorName}}', N'messaging', N'["clientName","vendorName","messageContent","dashboardUrl","platformName","platformUrl","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (6, N'message_client_to_vendor', N'Message from Client', 1, 8, 2, N'New Message from {{clientName}}', N'messaging', N'["vendorName","clientName","messageContent","dashboardUrl","platformName","platformUrl","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (7, N'payment_received_vendor', N'Payment Received', 1, 9, 2, N'Payment Received - {{amount}} from {{clientName}}', N'payment', N'["vendorName","clientName","amount","serviceName","eventDate","dashboardUrl","invoiceUrl","platformName","platformUrl","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (8, N'payment_confirmation_client', N'Payment Confirmation to Client', 1, 19, 2, N'Payment Confirmed - {{amount}} to {{vendorName}}', N'payment', N'["clientName","vendorName","amount","serviceName","eventDate","dashboardUrl","invoiceUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (9, N'booking_cancelled_client', N'Booking Cancelled - Client Notification', 1, 20, 2, N'Booking Cancelled - {{serviceName}}', N'booking', N'["clientName","vendorName","serviceName","eventDate","reason","refundAmount","searchUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (10, N'booking_cancelled_vendor', N'Booking Cancelled - Vendor Notification', 1, 21, 2, N'Booking Cancelled by {{clientName}}', N'booking', N'["vendorName","clientName","serviceName","eventDate","reason","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (11, N'vendor_application_admin', N'Vendor Application - Admin Notification', 1, 22, 2, N'New Vendor Application: {{businessName}}', N'admin', N'["applicantName","businessName","businessEmail","businessPhone","category","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (12, N'vendor_welcome', N'Vendor Welcome Email', 1, 23, 2, N'Welcome to {{platformName}}, {{vendorName}}', N'welcome', N'["vendorName","businessName","dashboardUrl","incompleteMessage","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (13, N'booking_confirmed_client', N'Booking Confirmed - Client Notification', 1, 24, 2, N'Booking Confirmed with {{vendorName}}', N'booking', N'["clientName","vendorName","serviceName","eventDate","eventLocation","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (14, N'booking_confirmed_vendor', N'Booking Confirmed - Vendor Notification', 1, 25, 2, N'Booking Confirmed - {{clientName}}', N'booking', N'["vendorName","clientName","serviceName","eventDate","eventLocation","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (15, N'vendor_approved', N'Vendor Profile Approved', 1, 26, 2, N'Your Profile is Approved - {{businessName}}', N'vendor', N'["vendorName","businessName","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (16, N'vendor_rejected', N'Vendor Profile Rejected', 1, 27, 2, N'Profile Review Update - {{businessName}}', N'vendor', N'["vendorName","businessName","rejectionReason","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (17, N'client_welcome', N'Client Welcome Email', 1, 28, 2, N'Welcome to {{platformName}}, {{clientName}}', N'welcome', N'["clientName","searchUrl","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (18, N'client_to_vendor', N'Client to Vendor Welcome', 1, 29, 2, N'Welcome to {{platformName}} as a Vendor, {{vendorName}}!', N'welcome', N'["vendorName","businessName","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (19, N'event_reminder', N'Event Reminder', 1, 30, 2, N'Reminder: Your event is in {{daysUntilEvent}}', N'reminder', N'["recipientName","daysUntilEvent","serviceName","eventDate","eventTime","location","otherPartyLabel","otherPartyName"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (20, N'booking_action_reminder', N'Booking Action Reminder', 1, 31, 2, N'Action Required: {{actionSubject}}', N'reminder', N'["recipientName","actionMessage","actionSubject","serviceName","eventDate","otherPartyLabel","otherPartyName","actionUrl","actionButtonText"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (21, N'analytics_summary', N'Analytics Summary', 1, 32, 2, N'Your {{periodLabel}} Performance Summary', N'analytics', N'["vendorName","periodLabel","periodRange","profileViews","profileViewsChange","totalBookings","bookingsChange","totalRevenue","revenueChange","conversionRate"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (22, N'account_suspended', N'Account Suspended', 1, 33, 2, N'Your {{platformName}} Account Has Been Suspended', N'account', N'["userName","suspensionReason"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (23, N'account_reactivated', N'Account Reactivated', 1, 34, 2, N'Your {{platformName}} Account Has Been Reactivated', N'account', N'["userName"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (24, N'client_to_vendor_welcome', N'Client to Vendor Welcome', 1, 29, 2, N'Welcome to {{platformName}} as a Vendor, {{vendorName}}!', N'welcome', N'["vendorName","businessName","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (25, N'password_reset', N'Password Reset Request', 1, 41, 2, N'Reset Your {{platformName}} Password', N'account', N'userName,resetUrl,expiryTime,platformName,currentYear,unsubscribeUrl,preferencesUrl', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (26, N'password_changed', N'Password Changed Confirmation', 1, 36, 2, N'Your {{platformName}} Password Has Been Changed', N'account', N'userName,platformName,currentYear', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (27, N'support_ticket_opened', N'Support Ticket Opened', 1, 37, 2, N'Support Ticket #{{ticketId}} - We Received Your Request', N'support', N'userName,ticketId,ticketSubject,ticketCategory,dashboardUrl,platformName,currentYear,unsubscribeUrl,preferencesUrl', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (28, N'support_ticket_in_progress', N'Support Ticket In Progress', 1, 38, 2, N'Support Ticket #{{ticketId}} - Now In Progress', N'support', N'userName,ticketId,ticketSubject,dashboardUrl,platformName,currentYear,unsubscribeUrl,preferencesUrl', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (29, N'support_ticket_closed', N'Support Ticket Closed', 1, 39, 2, N'Support Ticket #{{ticketId}} - Resolved', N'support', N'userName,ticketId,ticketSubject,resolution,dashboardUrl,platformName,currentYear,unsubscribeUrl,preferencesUrl', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (30, N'support_ticket_reply', N'Support Ticket Reply', 1, 40, 2, N'New Reply on Support Ticket #{{ticketId}}', N'support', N'userName,ticketId,replierName,replyPreview,dashboardUrl,platformName,currentYear,unsubscribeUrl,preferencesUrl', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (31, N'review_request', N'Post-Event Review Request', 1, 42, 2, N'How was your experience with {{vendorName}}?', N'review', N'["clientName","vendorName","serviceName","eventDate","reviewUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (32, N'support_ticket_confirmation', N'Support Ticket Confirmation', 1, 43, 2, N'Support Ticket Received - {{ticketNumber}}', N'support', N'userName,ticketNumber,ticketSubject,category,createdAt,platformName,currentYear,unsubscribeUrl,preferencesUrl', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (33, N'support_ticket_admin', N'Support Ticket Admin Notification', 1, 44, 2, N'New Support Ticket: {{ticketNumber}} - {{ticketSubject}}', N'support', N'ticketNumber,userName,userEmail,ticketSubject,category,priority,description,attachmentCount,createdAt,platformName,currentYear', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (34, N'support_message_received', N'Support Message Received', 1, 45, 2, N'New Message from Planbeau Support', N'support', N'["userName","messagePreview","dashboardUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (35, N'new_support_message', N'New Support Message Alert', 1, 46, 2, N'[SUPPORT] New Message from {{userName}}', N'support', N'["userName","userEmail","conversationId","messagePreview","adminUrl","platformName","platformUrl","currentYear","logoUrl"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (37, N'payment_failed', N'Payment Failed - Retry Request', 1, 47, 2, N'Action Required: Payment Failed for Your Booking', N'booking', N'recipientName,bookingId,serviceName,vendorName,amount,retryUrl', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (38, N'vendor_inactivity', N'Vendor Inactivity Alert', 1, 48, 2, N'We Miss You! Your Planbeau Profile Needs Attention', N'vendor', N'recipientName,vendorName,lastActiveDate,dashboardUrl', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (39, N'user_inactivity', N'User Inactivity Alert', 1, 49, 2, N'We Miss You! Come Back to Planbeau', N'user', N'recipientName,searchUrl,dashboardUrl', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (40, N'account_locked', N'Account Locked Notification', 1, 50, 2, N'Your Planbeau Account Has Been Locked', N'security', N'{{userName}},{{lockType}},{{lockReason}},{{supportUrl}},{{supportEmail}}', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (41, N'account_unlocked', N'Account Unlocked Notification', 1, 51, 2, N'Your Planbeau Account Has Been Unlocked', N'security', N'{{userName}},{{unlockReason}},{{dashboardUrl}}', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (42, N'chat_summary', N'Chat Summary', 1, 52, 2, N'Your Support Chat Summary - {{referenceNumber}}', N'support', N'["recipientName","referenceNumber","subject","category","conversationHtml","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (43, N'policy_warning', N'Policy Warning', 1, 53, 2, N'Warning: Your Message Was Blocked', N'admin', N'["userName","violationType","warningMessage","supportEmail","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (44, N'email_verification', N'Email Verification', 1, 54, 2, N'Verify Your Email - {{platformName}}', N'authentication', N'["userName","verificationUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (45, N'login_new_device', N'Login From New Device', 1, 55, 2, N'New Login Detected - {{platformName}}', N'authentication', N'["userName","deviceName","location","loginTime","secureAccountUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (46, N'booking_rescheduled', N'Booking Rescheduled', 1, 56, 2, N'Booking Rescheduled - {{serviceName}}', N'booking', N'["recipientName","serviceName","originalDate","originalTime","newDate","newTime","dashboardUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (47, N'invoice_sent', N'Invoice Sent', 1, 57, 2, N'Invoice from {{vendorName}} - {{amount}}', N'payment', N'["clientName","vendorName","invoiceNumber","serviceName","eventDate","amount","dueDate","paymentUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (48, N'refund_processed', N'Refund Processed', 1, 58, 2, N'Refund Processed - {{refundAmount}}', N'payment', N'["recipientName","refundAmount","serviceName","refundMethod","dashboardUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (49, N'payout_processed', N'Payout Processed', 1, 59, 2, N'Payout Sent - {{payoutAmount}}', N'payment', N'["vendorName","payoutAmount","lastFourDigits","arrivalDate","dashboardUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (50, N'new_review_received', N'New Review Received', 1, 60, 2, N'New {{rating}}-Star Review from {{clientName}}!', N'review', N'["vendorName","clientName","rating","starsHtml","reviewPreview","reviewUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (51, N'favorite_vendor_available', N'Favorite Vendor Available', 1, 61, 2, N'{{vendorName}} Has New Availability!', N'user', N'["clientName","vendorName","vendorCategory","availableDates","vendorProfileUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (52, N'vendor_profile_incomplete', N'Vendor Profile Incomplete', 1, 62, 2, N'Complete Your Profile to Start Receiving Bookings', N'vendor', N'["vendorName","completionPercentage","incompleteSectionsHtml","dashboardUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (53, N'account_deletion_requested', N'Account Deletion Requested', 1, 63, 2, N'Confirm Account Deletion - {{platformName}}', N'account', N'["userName","confirmDeletionUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (54, N'unread_messages_reminder', N'Unread Messages Reminder', 1, 64, 2, N'You Have {{unreadCount}} Unread Message(s)', N'messaging', N'["recipientName","unreadCount","messagePreviewsHtml","messagesUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (55, N'quote_received', N'Quote Received', 1, 65, 2, N'New Quote from {{vendorName}}', N'booking', N'["clientName","vendorName","serviceName","eventDate","quoteAmount","validUntil","quoteUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (56, N'receipt', N'Payment Receipt', 1, 66, 2, N'Receipt #{{receiptNumber}} - {{amount}}', N'payment', N'["clientName","receiptNumber","paymentDate","vendorName","serviceName","amount","paymentMethod","receiptUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (57, N'booking_reminder_24h', N'Booking Reminder 24h', 1, 67, 2, N'Your Event is Tomorrow!', N'booking', N'["recipientName","serviceName","eventDate","eventTime","location","dashboardUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (58, N'booking_reminder_1_week', N'Booking Reminder 1 Week', 1, 68, 2, N'Your Event is in 1 Week!', N'booking', N'["recipientName","serviceName","eventDate","vendorName","dashboardUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (59, N'subscription_renewal_reminder', N'Subscription Renewal Reminder', 1, 69, 2, N'Your {{planName}} Subscription Renews Soon', N'billing', N'["userName","planName","amount","renewalDate","subscriptionUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (60, N'subscription_cancelled', N'Subscription Cancelled', 1, 70, 2, N'Your {{planName}} Subscription Has Been Cancelled', N'billing', N'["userName","planName","accessEndDate","subscriptionUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (61, N'promotional_offer', N'Promotional Offer', 1, 71, 2, N'{{offerTitle}}', N'marketing', N'["recipientName","offerTitle","offerDescription","discountAmount","promoCode","expiryDate","offerUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (62, N'newsletter', N'Newsletter', 1, 72, 2, N'{{newsletterTitle}}', N'marketing', N'["recipientName","newsletterTitle","newsletterContent","readMoreUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (63, N'referral_invitation', N'Referral Invitation', 1, 73, 2, N'{{referrerName}} Invited You to PlanBeau!', N'referral', N'["referrerName","referralBonus","referralUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (64, N'referral_reward', N'Referral Reward', 1, 74, 2, N'You Earned a Referral Reward!', N'referral', N'["userName","referredName","rewardAmount","dashboardUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (65, N'dispute_opened', N'Dispute Opened', 1, 75, 2, N'Dispute Opened for Booking #{{bookingId}}', N'dispute', N'["recipientName","bookingId","serviceName","disputeReason","filedBy","disputeUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (66, N'dispute_resolved', N'Dispute Resolved', 1, 76, 2, N'Dispute Resolved for Booking #{{bookingId}}', N'dispute', N'["recipientName","bookingId","resolution","resolutionDetails","disputeUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (67, N'vendor_featured', N'Vendor Featured', 1, 77, 2, N'Congratulations! You are a Featured Vendor!', N'vendor', N'["vendorName","dashboardUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (68, N'booking_deposit_due', N'Booking Deposit Due', 1, 78, 2, N'Deposit Due for Your Booking with {{vendorName}}', N'payment', N'["clientName","vendorName","serviceName","eventDate","depositAmount","dueDate","paymentUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (69, N'final_payment_due', N'Final Payment Due', 1, 79, 2, N'Final Payment Due for Your Event with {{vendorName}}', N'payment', N'["clientName","vendorName","serviceName","eventDate","amountDue","dueDate","paymentUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (70, N'event_completed', N'Event Completed', 1, 80, 2, N'Your Event with {{vendorName}} is Complete!', N'booking', N'["clientName","vendorName","serviceName","eventDate","reviewUrl","platformName","currentYear"]', 1, CAST(N'2026-02-11 21:46:35.802' AS DateTime), CAST(N'2026-02-11 21:46:35.802' AS DateTime));
    INSERT [admin].[EmailTemplates] ([TemplateID], [TemplateKey], [TemplateName], [HeaderComponentID], [BodyComponentID], [FooterComponentID], [Subject], [Category], [AvailableVariables], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (71, N'vendor_badge_granted', N'Vendor Badge Granted', 1, 81, 2, N'Congratulations! You''ve Earned the {{badgeName}} Badge!', N'vendor', N'["vendorName","badgeName","businessName","badgeImageHtml","dashboardUrl","platformName","platformUrl","currentYear"]', 1, CAST(N'2026-02-12 22:15:00.000' AS DateTime), CAST(N'2026-02-12 22:15:00.000' AS DateTime));

    SET IDENTITY_INSERT [admin].[EmailTemplates] OFF;

    PRINT 'Inserted 70 records into [admin].[EmailTemplates].';
END
ELSE
BEGIN
    PRINT 'Table [admin].[EmailTemplates] already contains data. Skipping inserts.';
END
GO
